freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-3
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - sed -i.bak -e 's,/quarterly,/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y samurai pkgconf libevent
  matrix:
    - name: freebsd_clang
      test_script:
        - ./configure CC=cc || cat _build/.mkbuild/config.log
        - samu -C_build
    - name: freebsd_gcc
      gcc_script: pkg install -y gcc11
      test_script:
        - ./configure CC=gcc11 || cat _build/.mkbuild/config.log
        - samu -C_build

linux_task:
  container:
    image: gcc:latest
  env:
    CIRRUS_CLONE_SUBMODULES: true
  deps_script:
    - apt-get update && apt-get -y install bash ninja-build libssl-dev pkg-config libevent-dev
  matrix:
    - name: linux_clang
      clang_script:
        - apt-get -y install clang llvm
      test_script:
        - ./configure CC=clang || cat _build/.mkbuild/config.log
        - ninja -C_build parfetch
    - name: linux_gcc
      test_script:
        - ./configure CC=gcc || cat _build/.mkbuild/config.log
        - ninja -C_build parfetch
