= Changelog

All notable changes to _parfetch_ are documented in this file. The
sections should follow the order _Packaging_, _Added_, _Changed_,
_Fixed_ and _Removed_.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a ChangeLog].

== Unreleased

=== Added

* Support `MASTER_SITE_OVERRIDE` and `MASTER_SITE_FREEBSD`
* Support `RANDOMIZE_MASTER_SITES`
* Subsume `makesum` as well to make use of on-the-fly
  checksumming too and to skip the sha256(1) calls afterwards.
* When `PARFETCH_MAKESUM_KEEP_TIMESTAMP` is defined `makesum`
  will not update `TIMESTAMP` in `distinfo`. This can be useful
  when refreshing patches with no code changes.
* "Ephemeral" makesum through `PARFETCH_MAKESUM_EPHEMERAL`:
  Create/update `distinfo` but never save any distfiles. Note that
  the files are still downloaded completely to checksum them but
  `DISTDIR` is left untouched.
* Progress bar

=== Changed

* Speed up initial checksum: For already existing distfiles
  open them in non-blocking mode and do the checksumming
  asynchronously instead of one by one to reduce idle time.
  This speeds up the whole operation a little. Additionally
  switch to OpenSSL which is faster than OpenBSD's or FreeBSD's
  libmd implementations. Numbers for `makesum` in `x11/wezterm`:
  framework 7.35 s, parfetch before 4.83 s, parfetch after with
  OpenBSD's libmd 3.24 s, parfetch after with OpenSSL 2.02 s

=== Fixed

* Do not overwrite and break `checksum` and `makesum` if ports
  have custom `do-fetch` targets
* Overwrite targets only after `bsd.port.pre.mk`

== [a20211126] - 2021-11-26

No changelog for old releases.
